# -*- coding: utf-8 -*-
"""Breast_Cancer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yYN4aavlILLKWxOVSNGAX29GN_J5G4r
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()
dataset=pd.DataFrame(data.data,columns=data.feature_names)
dataset['target']=data.target
print(dataset.head())

plt.figure(figsize=(10,8))
sns.heatmap(dataset.corr(),cmap="coolwarm")
plt.title("correlation Heatmap")
plt.show()

dataset.hist(figsize=(12,10))
plt.show()

plt.figure(figsize=(12,6))
dataset.boxplot()
plt.xticks(rotation=90)
plt.title("outlier Detection")
plt.show()

Q1=dataset.quantile(0.25)
Q3=dataset.quantile(0.75)
IQR=Q3- Q1
dataset=dataset[~((dataset < (Q1 - 1.5 * IQR))|(dataset >(Q3 + 1.5 * IQR))).any(axis=1)]
print("Dataset Shape After Removing Outliers:",dataset.shape)

plt.figure(figsize=(12,6))
dataset.boxplot()
plt.xticks(rotation=90)
plt.title("outlier Detection")
plt.show()

x=dataset[["mean radius","mean texture"]].values
y=dataset["target"].values
plt.scatter(dataset["mean radius"],dataset["mean texture"],c=y)
plt.xlabel("mean radius")
plt.title("Feature visualization")
plt.show()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="entropy",random_state=0)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print("predictions:",y_pred)

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("confusion matrix:")
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

plt.scatter(x_train[:,0],x_train[:,1],c=y_train)
plt.xlabel("mean radius")
plt.ylabel("mean texture")
plt.title("Training set")
plt.show()

plt.scatter(x_test[:,0],x_test[:,1],c=y_test)
plt.xlabel("mean radius")
plt.ylabel("mean texture")
plt.title("Test set")
plt.show()

