# -*- coding: utf-8 -*-
"""Decision_Tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeJEYY-oHk2jhsWKLVirxdpyi-GjxkYw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/drive/MyDrive/diabetes.csv")
print(dataset.head())

plt.figure(figsize=(8,6))
sns.heatmap(dataset.corr(),annot=True)
plt.title("correlation heatmap")
plt.show()

dataset.hist(figsize=(10,8))
plt.show()

plt.figure(figsize=(10,6))
dataset.boxplot()
plt.title("outlier detection")
plt.show()

Q1=dataset.quantile(0.25)
Q3=dataset.quantile(0.75)
IQR=Q3-Q1
dataset=dataset[~((dataset <(Q1-1.5 * IQR))|(dataset > (Q3+1.5 * IQR)).any (axis=1))]
print("dataset shape after removing outliers:",dataset.shape)

plt.figure(figsize=(10,6))
dataset.boxplot()
plt.title("outlier detection")
plt.show()

x=dataset[["Glucose","BMI"]].values
y=dataset["Outcome"].values
plt.scatter(dataset["Glucose"],dataset["BMI"],c=y)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.show()

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train ,Y_test= train_test_split(
    x,y,test_size=0.25,random_state=0
    )

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy',random_state=0)
model.fit(X_train,Y_train)

y_pred=model.predict(X_test)
print("predictions:", y_pred)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print("confusion matrix:")
print(cm)
accuracy = accuracy_score(Y_test,y_pred)
print("Accuracy ",accuracy)

plt.scatter(X_train[:,0],X_train[:,1],c=Y_train)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.title("Training set")
plt.show()

plt.scatter(X_test[:,0],X_test[:,1],c=Y_test)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.title("Test set")
plt.show()